### ISSUE TITLE
Add a system to add {nickname}, {count} and {getGenderedSuffixes} with Generator

### ISSUE THREAD

**Issue by samuel-duhaime** [chairemobilite/evolution#416] opened 2024-04-03 20:18 UTC
# Issue

## Description
We should be able to use {nickname}, {count}, and {getGenderedSuffixes} easily with Generator directly to the label.

## Justification
Right now, I need to use CustomWidget when we use {nickname}, when we need to count the number of person or when we need to get the generedSuffixes of the person. We need a better solution, and Generator could help us, build something great.

## Possible implementation 
We could do something similar to this code from Od_Mtl_2023.

```Typescript
label: (t: TFunction, interview, path) => {
        const nickname = surveyHelperNew.getResponse(interview, path, t('survey:noNickname'), '../nickname');
        const person = surveyHelperNew.getResponse(interview, path, null, '../');
        return t('household:Travail', {
            count: helper.countPersons(interview),
            ...frontendHelper.getGenderedSuffixes(person, t)
        });
    },
```

**Comment by tahini** [comment] 2024-04-11 22:26
duplicate of #432, which is fixed

**Closed by tahini** 2024-04-11 22:26 UTC
Labels: generator
